name: flat_3d_button
description: A simple 3D flat button with click animation!
version: 1.0.0
homepage: https://github.com/rijfas/flat_3d_button
repository: https://github.com/rijfas/flat_3d_button

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
